- name: Configurar VM de Azure con Podman
  hosts: azure_vm
  become: true

  tasks:
    - name: Descargar el binario de Caddy
      get_url:
        url: https://caddyserver.com/api/download?os=linux&arch=amd64
        dest: /tmp/caddy
        mode: '0755'

    - name: Mover el binario de Caddy a /usr/bin/
      copy:
        src: /tmp/caddy
        dest: /usr/bin/caddy
        mode: '0755'
        remote_src: yes

    - name: Crear el archivo de configuración de Caddy
      copy:
        content: |
          [Unit]
          Description=Caddy Web Server
          Documentation=https://caddyserver.com/docs/
          After=network.target network-online.target
          Requires=network-online.target

          [Service]
          User=caddy
          Group=caddy
          WorkingDirectory=/var/www
          ExecStart=/usr/bin/caddy run --environ --config /etc/caddy/Caddyfile
          ExecReload=/usr/bin/caddy reload --config /etc/caddy/Caddyfile
          TimeoutStopSec=5s
          LimitNOFILE=1048576
          LimitNPROC=512
          PrivateTmp=true
          PrivateDevices=true
          ProtectSystem=full
          AmbientCapabilities=CAP_NET_BIND_SERVICE

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/caddy.service
        mode: '0644'

    - name: Crear el usuario y grupo de Caddy
      user:
        name: caddy
        group: caddy
        system: yes
        create_home: no

    - name: Crear el directorio de configuración de Caddy
      file:
        path: /etc/caddy
        state: directory

    - name: Crear el directorio de trabajo de Caddy
      file:
        path: /var/www
        state: directory

    - name: Crear un ejemplo de Caddyfile
      copy:
        content: |
          {
            admin localhost:2019
          }

          localhost {
            respond "Hello, world!"
          }
        dest: /etc/caddy/Caddyfile
        mode: '0644'

    - name: Recargar systemd
      systemd:
        daemon_reload: yes

    - name: Habilitar e iniciar el servicio Caddy
      systemd:
        name: caddy
        enabled: yes
        state: started